// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ForumWebsite.Models
{
    public partial class Complaint
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int? EmpId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Title { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PostStatus { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Type { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfComplaint { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }
        public int? Escalation { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfEscalation { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfResolution { get; set; }
        public int? WithinTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ResolvedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
    }
}