// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ForumWebsite.Models
{
    public partial class ComplaintComment
    {
        [Key]
        public int Id { get; set; }
        [Unicode(false)]
        public string CommentText { get; set; }
        public int? ComplaintId { get; set; }
        [Unicode(false)]
        public string CommentBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
    }
}